version: "3.7"
services:
  go-grpc:
    build:
      context: ./client-test/
      dockerfile: Dockerfile
    container_name: "go-grpc"
    volumes:
      - ./client-test:/go-grpc
      - ./src/main/proto:/go-grpc/proto
    tty: true
    privileged: true

  todo-dynamodb:
    image: amazon/dynamodb-local
    container_name: 'todo-dynamodb'
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath .
    ports:
      - 8000:8000

  batch-notebook:
    build: ./notebook
    container_name: "batch-notebook"
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./notebook:/home/jovyan/work
      # ローカル認証情報
      - ~/.aws:/home/jovyan/.aws
    command: start.sh jupyter lab --NotebookApp.token=''
