environments:
  profile: Local

server:
  tomcat:
    max-threads: 200

spring:
  devtools:
    livereload:
      enabled: false
  data:
    dynamodb:
      entity2ddl:
        auto: create-only
        gsiProjectionType: ALL
        readCapacity: 1
        writeCapacity: 1
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis